# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_nood1_3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form_nood1_3(object):
    def setupUi(self, Form_nood1_3):
        Form_nood1_3.setObjectName(_fromUtf8("Form_nood1_3"))
        Form_nood1_3.resize(456, 416)
        self.label = QtGui.QLabel(Form_nood1_3)
        self.label.setGeometry(QtCore.QRect(20, 10, 421, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton = QtGui.QPushButton(Form_nood1_3)
        self.pushButton.setGeometry(QtCore.QRect(320, 370, 121, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(Form_nood1_3)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 370, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(Form_nood1_3)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 370, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(Form_nood1_3)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 370, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.groupBox = QtGui.QGroupBox(Form_nood1_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 431, 291))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 56, 12))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.textEdit_4 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_4.setGeometry(QtCore.QRect(130, 110, 291, 16))
        self.textEdit_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_4.setObjectName(_fromUtf8("textEdit_4"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 81, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.textEdit_7 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_7.setGeometry(QtCore.QRect(130, 230, 291, 16))
        self.textEdit_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_7.setObjectName(_fromUtf8("textEdit_7"))
        self.textEdit_5 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_5.setGeometry(QtCore.QRect(130, 170, 291, 16))
        self.textEdit_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_5.setObjectName(_fromUtf8("textEdit_5"))
        self.textEdit_6 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_6.setGeometry(QtCore.QRect(130, 140, 291, 16))
        self.textEdit_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_6.setObjectName(_fromUtf8("textEdit_6"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 170, 81, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.textEdit = QtGui.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(130, 20, 291, 16))
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 56, 12))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.textEdit_3 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_3.setGeometry(QtCore.QRect(130, 80, 291, 16))
        self.textEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.textEdit_8 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_8.setGeometry(QtCore.QRect(130, 200, 291, 16))
        self.textEdit_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_8.setObjectName(_fromUtf8("textEdit_8"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 230, 91, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 56, 12))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 111, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.textEdit_9 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_9.setGeometry(QtCore.QRect(130, 260, 291, 16))
        self.textEdit_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_9.setObjectName(_fromUtf8("textEdit_9"))
        self.textEdit_2 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_2.setGeometry(QtCore.QRect(130, 50, 291, 16))
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 262, 81, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 56, 12))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.groupBox.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()

        self.retranslateUi(Form_nood1_3)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Form_nood1_3.dialog_add)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), Form_nood1_3.dialog_chang)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), Form_nood1_3.dialog_delete)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form_nood1_3.slot1_nood1)
        QtCore.QMetaObject.connectSlotsByName(Form_nood1_3)

    def retranslateUi(self, Form_nood1_3):
        Form_nood1_3.setWindowTitle(_translate("Form_nood1_3", "Form", None))
        self.label.setText(_translate("Form_nood1_3", "휴게소 시설 정보(추가, 수정, 삭제)", None))
        self.pushButton.setText(_translate("Form_nood1_3", "뒤로가기", None))
        self.pushButton_2.setText(_translate("Form_nood1_3", "추가", None))
        self.pushButton_3.setText(_translate("Form_nood1_3", "수정", None))
        self.pushButton_4.setText(_translate("Form_nood1_3", "삭제", None))
        self.groupBox.setTitle(_translate("Form_nood1_3", "정보 입력", None))
        self.label_4.setText(_translate("Form_nood1_3", "휴게소명", None))
        self.label_7.setText(_translate("Form_nood1_3", "경정비유무", None))
        self.label_9.setText(_translate("Form_nood1_3", "브랜드", None))
        self.label_2.setText(_translate("Form_nood1_3", "노선명", None))
        self.label_8.setText(_translate("Form_nood1_3", "화물휴게소유무", None))
        self.label_3.setText(_translate("Form_nood1_3", "방향", None))
        self.label_6.setText(_translate("Form_nood1_3", "편의시설 (구분 \'|\')", None))
        self.label_10.setText(_translate("Form_nood1_3", "대표음식", None))
        self.label_5.setText(_translate("Form_nood1_3", "전화번호", None))

