# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facility_edit.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form_nood1_3(object):
    def setupUi(self, Form_nood1_3):
        Form_nood1_3.setObjectName(_fromUtf8("Form_nood1_3"))
        Form_nood1_3.resize(600, 400)
        Form_nood1_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label = QtGui.QLabel(Form_nood1_3)
        self.label.setGeometry(QtCore.QRect(20, 10, 491, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton = QtGui.QPushButton(Form_nood1_3)
        self.pushButton.setGeometry(QtCore.QRect(440, 360, 121, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget = QtGui.QTabWidget(Form_nood1_3)
        self.tabWidget.setGeometry(QtCore.QRect(20, 50, 541, 291))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.add = QtGui.QWidget()
        self.add.setObjectName(_fromUtf8("add"))
        self.groupBox = QtGui.QGroupBox(self.add)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 521, 251))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 65, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.textEdit_4 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_4.setGeometry(QtCore.QRect(170, 95, 330, 16))
        self.textEdit_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_4.setObjectName(_fromUtf8("textEdit_4"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 195, 81, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.textEdit_5 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_5.setGeometry(QtCore.QRect(170, 145, 330, 16))
        self.textEdit_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_5.setObjectName(_fromUtf8("textEdit_5"))
        self.textEdit_6 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_6.setGeometry(QtCore.QRect(170, 120, 330, 16))
        self.textEdit_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_6.setObjectName(_fromUtf8("textEdit_6"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 145, 81, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.textEdit = QtGui.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(170, 20, 330, 16))
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 71, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.textEdit_3 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_3.setGeometry(QtCore.QRect(170, 70, 330, 16))
        self.textEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 91, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 45, 56, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 141, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.textEdit_9 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_9.setGeometry(QtCore.QRect(170, 170, 330, 16))
        self.textEdit_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_9.setObjectName(_fromUtf8("textEdit_9"))
        self.textEdit_2 = QtGui.QTextEdit(self.groupBox)
        self.textEdit_2.setGeometry(QtCore.QRect(170, 45, 330, 16))
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 170, 81, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 95, 65, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(170, 195, 81, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.buttonGroup = QtGui.QButtonGroup(Form_nood1_3)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(220, 195, 90, 20))
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.buttonGroup.addButton(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(220, 220, 90, 20))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.buttonGroup_2 = QtGui.QButtonGroup(Form_nood1_3)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(170, 220, 81, 20))
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.buttonGroup_2.addButton(self.radioButton_4)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 220, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.tabWidget.addTab(self.add, _fromUtf8(""))
        self.change = QtGui.QWidget()
        self.change.setObjectName(_fromUtf8("change"))
        self.groupBox_2 = QtGui.QGroupBox(self.change)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 521, 251))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 70, 65, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.textEdit_7 = QtGui.QTextEdit(self.groupBox_2)
        self.textEdit_7.setGeometry(QtCore.QRect(170, 95, 330, 16))
        self.textEdit_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_7.setObjectName(_fromUtf8("textEdit_7"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 195, 81, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.textEdit_8 = QtGui.QTextEdit(self.groupBox_2)
        self.textEdit_8.setGeometry(QtCore.QRect(170, 145, 330, 16))
        self.textEdit_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_8.setObjectName(_fromUtf8("textEdit_8"))
        self.textEdit_10 = QtGui.QTextEdit(self.groupBox_2)
        self.textEdit_10.setGeometry(QtCore.QRect(170, 120, 330, 16))
        self.textEdit_10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_10.setObjectName(_fromUtf8("textEdit_10"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 145, 81, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.textEdit_11 = QtGui.QTextEdit(self.groupBox_2)
        self.textEdit_11.setGeometry(QtCore.QRect(170, 20, 330, 16))
        self.textEdit_11.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_11.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_11.setObjectName(_fromUtf8("textEdit_11"))
        self.textEdit_12 = QtGui.QTextEdit(self.groupBox_2)
        self.textEdit_12.setGeometry(QtCore.QRect(170, 70, 330, 16))
        self.textEdit_12.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_12.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_12.setObjectName(_fromUtf8("textEdit_12"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 220, 91, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 45, 56, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 120, 141, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.textEdit_13 = QtGui.QTextEdit(self.groupBox_2)
        self.textEdit_13.setGeometry(QtCore.QRect(170, 170, 330, 16))
        self.textEdit_13.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_13.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_13.setObjectName(_fromUtf8("textEdit_13"))
        self.textEdit_14 = QtGui.QTextEdit(self.groupBox_2)
        self.textEdit_14.setGeometry(QtCore.QRect(170, 45, 330, 16))
        self.textEdit_14.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_14.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_14.setObjectName(_fromUtf8("textEdit_14"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 170, 81, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 95, 65, 20))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.radioButton_5 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_5.setGeometry(QtCore.QRect(170, 195, 81, 20))
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.buttonGroup_3 = QtGui.QButtonGroup(Form_nood1_3)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.radioButton_5)
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_6.setGeometry(QtCore.QRect(220, 195, 90, 20))
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.buttonGroup_3.addButton(self.radioButton_6)
        self.radioButton_7 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_7.setGeometry(QtCore.QRect(220, 220, 90, 20))
        self.radioButton_7.setChecked(False)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.buttonGroup_4 = QtGui.QButtonGroup(Form_nood1_3)
        self.buttonGroup_4.setObjectName(_fromUtf8("buttonGroup_4"))
        self.buttonGroup_4.addButton(self.radioButton_7)
        self.radioButton_8 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_8.setGeometry(QtCore.QRect(170, 220, 81, 20))
        self.radioButton_8.setChecked(True)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.buttonGroup_4.addButton(self.radioButton_8)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 220, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 71, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.tabWidget.addTab(self.change, _fromUtf8(""))
        self.delete = QtGui.QWidget()
        self.delete.setObjectName(_fromUtf8("delete"))
        self.textEdit_15 = QtGui.QTextEdit(self.delete)
        self.textEdit_15.setGeometry(QtCore.QRect(90, 10, 381, 31))
        self.textEdit_15.setObjectName(_fromUtf8("textEdit_15"))
        self.comboBox = QtGui.QComboBox(self.delete)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.pushButton_4 = QtGui.QPushButton(self.delete)
        self.pushButton_4.setGeometry(QtCore.QRect(430, 230, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.tableWidget_2 = QtGui.QTableWidget(self.delete)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 50, 511, 171))
        self.tableWidget_2.setMouseTracking(False)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(27)
        self.pushButton_5 = QtGui.QPushButton(self.delete)
        self.pushButton_5.setGeometry(QtCore.QRect(480, 10, 41, 31))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.tabWidget.addTab(self.delete, _fromUtf8(""))

        self.retranslateUi(Form_nood1_3)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), Form_nood1_3.dialog_delete)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form_nood1_3.slot1_nood1)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Form_nood1_3.dialog_add)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), Form_nood1_3.dialog_chang)
        QtCore.QMetaObject.connectSlotsByName(Form_nood1_3)

    def retranslateUi(self, Form_nood1_3):
        Form_nood1_3.setWindowTitle(_translate("Form_nood1_3", "Form", None))
        self.label.setText(_translate("Form_nood1_3", "휴게소 시설 정보(추가, 수정, 삭제)", None))
        self.pushButton.setText(_translate("Form_nood1_3", "뒤로가기", None))
        self.groupBox.setTitle(_translate("Form_nood1_3", "정보 입력", None))
        self.label_4.setText(_translate("Form_nood1_3", "휴게소명", None))
        self.label_7.setText(_translate("Form_nood1_3", "경정비유무", None))
        self.label_9.setText(_translate("Form_nood1_3", "브랜드", None))
        self.label_2.setText(_translate("Form_nood1_3", "고속도로명", None))
        self.label_8.setText(_translate("Form_nood1_3", "화물휴게소유무", None))
        self.label_3.setText(_translate("Form_nood1_3", "방향", None))
        self.label_6.setText(_translate("Form_nood1_3", "편의시설 (구분 \'|\')", None))
        self.label_10.setText(_translate("Form_nood1_3", "대표음식", None))
        self.label_5.setText(_translate("Form_nood1_3", "전화번호", None))
        self.radioButton.setText(_translate("Form_nood1_3", "O", None))
        self.radioButton_2.setText(_translate("Form_nood1_3", "X", None))
        self.radioButton_3.setText(_translate("Form_nood1_3", "X", None))
        self.radioButton_4.setText(_translate("Form_nood1_3", "O", None))
        self.pushButton_2.setText(_translate("Form_nood1_3", "추가", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.add), _translate("Form_nood1_3", "추가", None))
        self.groupBox_2.setTitle(_translate("Form_nood1_3", "정보 입력", None))
        self.label_11.setText(_translate("Form_nood1_3", "휴게소명", None))
        self.label_12.setText(_translate("Form_nood1_3", "경정비유무", None))
        self.label_13.setText(_translate("Form_nood1_3", "브랜드", None))
        self.label_15.setText(_translate("Form_nood1_3", "화물휴게소유무", None))
        self.label_16.setText(_translate("Form_nood1_3", "방향", None))
        self.label_17.setText(_translate("Form_nood1_3", "편의시설 (구분 \'|\')", None))
        self.label_18.setText(_translate("Form_nood1_3", "대표음식", None))
        self.label_19.setText(_translate("Form_nood1_3", "전화번호", None))
        self.radioButton_5.setText(_translate("Form_nood1_3", "O", None))
        self.radioButton_6.setText(_translate("Form_nood1_3", "X", None))
        self.radioButton_7.setText(_translate("Form_nood1_3", "X", None))
        self.radioButton_8.setText(_translate("Form_nood1_3", "O", None))
        self.pushButton_3.setText(_translate("Form_nood1_3", "수정", None))
        self.label_14.setText(_translate("Form_nood1_3", "고속도로명", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.change), _translate("Form_nood1_3", "수정", None))
        self.comboBox.setItemText(0, _translate("Form_nood1_3", "휴게소명", None))
        self.comboBox.setItemText(1, _translate("Form_nood1_3", "고속도로명", None))
        self.pushButton_4.setText(_translate("Form_nood1_3", "삭제", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form_nood1_3", "휴게소명", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form_nood1_3", "고속도로명", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form_nood1_3", "방향", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form_nood1_3", "보유 편의시설", None))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form_nood1_3", "전화번호", None))
        self.pushButton_5.setText(_translate("Form_nood1_3", "검색", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.delete), _translate("Form_nood1_3", "삭제", None))

